config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :shoot_locations
  resources :actors
  resources :series

  root "series#index"
  get '/search', to: 'series#search', as: 'search'
end

app/models/shoot_location.rb
class ShootLocation < ApplicationRecord
  belongs_to :series
  validates_presence_of :name, :series
end

app/controllers/shoot_locations_controller.rb
class ShootLocationsController < ApplicationController
  before_action :set_shoot_location, only: %i[ show edit update destroy ]

  # GET /shoot_locations or /shoot_locations.json
  def index
    @shoot_locations = ShootLocation.all
  end

  # GET /shoot_locations/1 or /shoot_locations/1.json
  def show
  end

  # GET /shoot_locations/new
  def new
    @shoot_location = ShootLocation.new
  end

  # GET /shoot_locations/1/edit
  def edit
  end

  # POST /shoot_locations or /shoot_locations.json
  def create
    @shoot_location = ShootLocation.new(shoot_location_params)

    respond_to do |format|
      if @shoot_location.save
        format.html { redirect_to shoot_location_url(@shoot_location), notice: "Shoot location was successfully created." }
        format.json { render :show, status: :created, location: @shoot_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shoot_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoot_locations/1 or /shoot_locations/1.json
  def update
    respond_to do |format|
      if @shoot_location.update(shoot_location_params)
        format.html { redirect_to shoot_location_url(@shoot_location), notice: "Shoot location was successfully updated." }
        format.json { render :show, status: :ok, location: @shoot_location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shoot_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoot_locations/1 or /shoot_locations/1.json
  def destroy
    @shoot_location.destroy

    respond_to do |format|
      format.html { redirect_to shoot_locations_url, notice: "Shoot location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoot_location
      @shoot_location = ShootLocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shoot_location_params
      params.require(:shoot_location).permit(:name, :series_id)
    end
end

app/helpers/shoot_locations_helper.rb
module ShootLocationsHelper
end

app/views/shoot_locations/_form.html.erb
<%= form_with(model: shoot_location) do |form| %>
  <% if shoot_location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shoot_location.errors.count, "error") %> prohibited this shoot_location from being saved:</h2>

      <ul>
        <% shoot_location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :series_id, style: "display: block" %>
    <%= form.text_field :series_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shoot_locations/_shoot_location.html.erb
<div id="<%= dom_id shoot_location %>">
  <p>
    <strong>Name:</strong>
    <%= shoot_location.name %>
  </p>

  <p>
    <strong>Series:</strong>
    <%= shoot_location.series_id %>
  </p>

</div>

app/views/shoot_locations/edit.html.erb
<h1>Editing shoot location</h1>

<%= render "form", shoot_location: @shoot_location %>

<br>

<div>
  <%= link_to "Show this shoot location", @shoot_location %> |
  <%= link_to "Back to shoot locations", shoot_locations_path %>
</div>

app/views/shoot_locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shoot locations</h1>

<div id="shoot_locations">
  <% @shoot_locations.each do |shoot_location| %>
    <%= render shoot_location %>
    <p>
      <%= link_to "Show this shoot location", shoot_location %>
    </p>
  <% end %>
</div>

<%= link_to "New shoot location", new_shoot_location_path %>

app/views/shoot_locations/new.html.erb
<h1>New shoot location</h1>

<%= render "form", shoot_location: @shoot_location %>

<br>

<div>
  <%= link_to "Back to shoot locations", shoot_locations_path %>
</div>

app/views/shoot_locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shoot_location %>

<div>
  <%= link_to "Edit this shoot location", edit_shoot_location_path(@shoot_location) %> |
  <%= link_to "Back to shoot locations", shoot_locations_path %>

  <%= button_to "Destroy this shoot location", @shoot_location, method: :delete %>
</div>