config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :shoot_locations
  resources :actors
  resources :series

  root "series#index"
  get '/search', to: 'series#search', as: 'search'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
    if !@series.present?
      redirect_to root_path, notice: 'Series not found.'
    end
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @series = nil
    if params[:search].present?
      search_key = '%' + params[:search].downcase + '%'
      @series = Series.joins(:actors).where("lower(actors.name) LIKE ?", search_key)
    end

    @series
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:title, :genre, :seasons, :first_release, :director, :country, :description)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :seasons, style: "display: block" %>
    <%= form.number_field :seasons %>
  </div>

  <div>
    <%= form.label :first_release, style: "display: block" %>
    <%= form.date_field :first_release %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/series/_jumbo.html.erb
<div class="row align-items-md-stretch">
    <div class="col-md-6">
    <div class="h-100 p-5 bg-warning rounded-3">
        <h2>What to watch next?</h2>
        <p>Our experts reviews would guide you to choose the best</p>
    </div>
    </div>
    <div class="col-md-6">
    <div class="h-100 p-5 bg-light border rounded-3">
        <h2>Interested in details?</h2>
        <p>Our data will help you to lear more about your best series</p>
    </div>
    </div>
</div>

app/views/series/_list.html.erb
<div class="py-5" id="series">
    <h2 class="pb-2 border-bottom">Latest Series</h2>
    <div class="row row-cols-1 row-cols-lg-3 py-3">
        <% @series.each do |series| %>
            <div class="col">
                <div class="bg-light p-5 border rounded-3">
                    <div class="row">
                        <div class="col-10">
                            <h3><%= series.title %></h3>
                        </div>
                        <div class="col-2">
                            <span class="badge rounded-pill bg-info text-dark"><%= series.over_all_rating %></span>
                        </div>
                        <p><%= truncate(series.description, length: 100) %></p>
                        <%= link_to "Show", series, class: 'icon-link '%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/series/_search_form.html.erb
<div class='container mt-5 py-5 h-100 p-5 text-dark bg-light rounded-3 border'>
    <div class='row'>
        <div class='col text-dark'>
            <h2>Looking for actors newest series?</h2>
            <p>
                We offer multiple ways to find your favorite actors newest series, you can search by actor name and we do the needful.
            </p>
        </div>
        <div class='col'>
            <%= form_tag search_path, method: :get, class: 'row mx-auto my-auto' do %>
                <div class="col">
                    <%= search_field_tag :search, params[:search], label: false, required: true, placeholder: "Enter actor name", class: 'form-control form-control-lg' %>
                </div>
                <div class="col">    
                    <%= submit_tag 'Search', class:'btn btn-primary btn-lg' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/series/_series.html.erb
<div class="card bg-light" id="<%= dom_id series %>">
  <div class="card-body">
    <h3 class="card-title"><%= series.title %></h3>
    <br>
    <strong>Rating: </strong>
    <span class="badge rounded-pill bg-info text-dark"><%= series.over_all_rating %></span>
    
    <span> |
    <strong>Genre:</strong>
    <%= series.genre %>
    </span>

    <span> |
      <strong>Seasons:</strong>
      <%= series.seasons %>
    </span>

    <span> |
      <strong>First release:</strong>
      <%= series.first_release %>
    </span>

    <span> |
      <strong>Director:</strong>
      <%= series.director %>
    </span>

    <span> |
      <strong>Country:</strong>
      <%= series.country %>
    </span>
    <hr>
    <strong>Actors: </strong>
    <% series.actors.map(&:name).each do |actor| %>
        <span><%= actor %>, </span>
    <% end %>
    <hr>
    <strong>Shooting Locations: </strong>
    <% series.shoot_locations.map(&:name).each do |location| %>
        <span><%= location %>, </span>
    <% end %>
    <hr>
    <p><strong>About:</strong></p>
    <p class="card-text"><%= series.description %></p>
  </div>

  <div class='card-footer'>
    <%= link_to "Edit", edit_series_path(series), class: "btn btn-primary" %>
  </div>
</div>

app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this series", @series %> |
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/index.html.erb
<%= render 'jumbo' %>
<%= render 'search_form' %>
<%= render 'list' %>

app/views/series/new.html.erb
<h1>New series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/search.html.erb
<div class="pt-4" id="series">
    <h2 class="pb-2 border-bottom">Search Results</h2>
    <div class="row row-cols-1 py-3">
        <% if @series.present? %>
            <% @series.each do |series| %>
                <div class="col">
                    <div class="bg-light p-5 border rounded-3">
                        <div class="row">
                            <div class="col-10">
                                <h3><%= series.title %></h3>
                            </div>
                            <div class="col-2">
                                <span class="badge rounded-pill bg-info text-dark"><%= series.over_all_rating %></span>
                            </div>
                            <p><%= truncate(series.description, length: 100) %></p>
                            <%= link_to "Show", series, class: 'icon-link '%>
                        </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <div class="col text-center">
                <h3>No results found</h3>
            </div>
        <% end %>
    </div>
</div>

app/views/series/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @series %>